pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/cloud-banking-lab/account-service.git'
            }
        }
        stage('Build Docker Image') {
            steps {
                script {
                    docker.build("account-service:latest")
                }
            }
        }
        stage('Run Tests') {
            steps {
                sh 'pytest ./app/tests'
            }
        }
        stage('Push to Docker Hub') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'docker-hub', usernameVariable: 'USER', passwordVariable: 'PASS')]) {
                    sh 'docker login -u mazulu -p Bassie_07'
                    sh 'docker tag account-service:latest mazulu/account-service:latest'
                    sh 'docker push mazulu/account-service:latest'
                }
            }
        }
    }
}
