environment {
    ACCOUNT_IMAGE = "mazulu/account-service"
    TAG = "latest"
}

stages {

    stage('Checkout Code') {
        steps {
            checkout scm
        }
    }

    stage('Build Account Service') {
        steps {
            dir('account-service') {
                sh 'mvn clean package'
            }
        }
    }

    stage('Docker Build') {
        steps {
            sh 'docker build -t $ACCOUNT_IMAGE:$TAG ./account-service'
        }
    }

    stage('Push to Docker Hub') {
        steps {
            withCredentials([usernamePassword(
                credentialsId: 'dockerhub-credentials',
                usernameVariable: 'DOCKER_USER',
                passwordVariable: 'DOCKER_PASS'
            )]) {
                sh 'echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin'
                sh 'docker push $ACCOUNT_IMAGE:$TAG'
            }
        }
    }
}
